//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension GardenAPI.Worlds {

    /**
    Creates the world

    This will return all of the worlds
    */
    public enum CreateWorld {

        public static let service = APIService<Response>(id: "createWorld", tag: "Worlds", method: "POST", path: "/world", hasBody: true)

        public final class Request: APIRequest<Response> {

            public var body: ClientSideWorld?

            public init(body: ClientSideWorld?, encoder: RequestEncoder? = nil) {
                self.body = body
                super.init(service: CreateWorld.service) { defaultEncoder in
                    return try (encoder ?? defaultEncoder).encode(body)
                }
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = [World]

            /** The world has been created */
            case status200([World])

            public var success: [World]? {
                switch self {
                case .status200(let response): return response
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode([World].self, from: data))
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
