//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class Anchor: APIModel {

    public var title: String

    public var metadata: [AnchorMetadata]

    public var id: String?

    public init(title: String, metadata: [AnchorMetadata], id: String? = nil) {
        self.title = title
        self.metadata = metadata
        self.id = id
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        title = try container.decode("title")
        metadata = try container.decodeArray("metadata")
        id = try container.decodeIfPresent("id")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(title, forKey: "title")
        try container.encode(metadata, forKey: "metadata")
        try container.encodeIfPresent(id, forKey: "id")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? Anchor else { return false }
      guard self.title == object.title else { return false }
      guard self.metadata == object.metadata else { return false }
      guard self.id == object.id else { return false }
      return true
    }

    public static func == (lhs: Anchor, rhs: Anchor) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
