//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class AnchorMetadata: APIModel {

    public var id: String?

    public var text: String?

    public init(id: String? = nil, text: String? = nil) {
        self.id = id
        self.text = text
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        id = try container.decodeIfPresent("id")
        text = try container.decodeIfPresent("text")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(id, forKey: "id")
        try container.encodeIfPresent(text, forKey: "text")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? AnchorMetadata else { return false }
      guard self.id == object.id else { return false }
      guard self.text == object.text else { return false }
      return true
    }

    public static func == (lhs: AnchorMetadata, rhs: AnchorMetadata) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
