//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ClientSideWorld: APIModel {

    public var title: String

    public var data: String

    public init(title: String, data: String) {
        self.title = title
        self.data = data
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        title = try container.decode("title")
        data = try container.decode("data")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(title, forKey: "title")
        try container.encode(data, forKey: "data")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ClientSideWorld else { return false }
      guard self.title == object.title else { return false }
      guard self.data == object.data else { return false }
      return true
    }

    public static func == (lhs: ClientSideWorld, rhs: ClientSideWorld) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
